/**
 * Created by Andrey Zubov on 19.03.2021.
 */

public with sharing class RunProviderRequest {

//    public static void runSign(){
//        SignFlow signFlow = getSignFlow('Russia');
//        signFlow.signDocument();
////        // Request Docusign
////        ProviderConnection docusignProvider = new ProviderConnection('ProviderDocusign');
////        docusignProvider.requestProvider();
////        // Request Docupost
////        ProviderConnection docupostProvider = new ProviderConnection('ProviderDocupost');
////        docupostProvider.requestProvider();
//    }
//
//    private static SignFlow getSignFlow(String locale){
//        SignFlowFactory signFactory = new SignFlowFactory();
//        if(locale == 'Russia'){
//            signFactory = new russiaSignFactory();
//        } else if(locale == 'France') {
//            signFactory = new franceSignFactory();
//        }
//        return new SignFlow(signFactory);
//    }

}